import { getApprovedResource } from "../source-registry.ts";
import { BaseSourceAdapter } from "./base.ts";
import type { AdapterDiagnostic, AdapterExecutionContext, IntegrityReport } from "./types.ts";
import { assertUnique11586Applications, normalize11586Application, parse11586Csv, type NormalizedListingApplication11586, type Source11586Row } from "../../source-verification/source-11586.ts";

export type ListingApplicationStage11586 = "applied" | "listing_review_completed" | "board_approved" | "contract_filed_or_regulator_approved" | "listed_for_trading";
export type NormalizedListingApplicationWithStage11586 = NormalizedListingApplication11586 & { stage: ListingApplicationStage11586 };

function deriveStage(record: NormalizedListingApplication11586): ListingApplicationStage11586 { if (record.listingDate) return "listed_for_trading"; if (record.listingContractApprovalOrFilingDate) return "contract_filed_or_regulator_approved"; if (record.boardApprovalDate) return "board_approved"; if (record.listingReviewDate) return "listing_review_completed"; return "applied"; }

export class Source11586CsvAdapter extends BaseSourceAdapter<Source11586Row, NormalizedListingApplicationWithStage11586> {
  readonly sourceId = "11586"; readonly resourceId = "11586-csv"; readonly adapterVersion = "11586-csv-adapter-v1"; readonly rawSchemaVersion = "dataset-11586-raw-v1"; readonly domainSchemaVersion = "listing-application-11586-v1";
  private readonly fixtureResponse?: { body: Uint8Array; contentType: string; fetchedAt: string; sha256: `sha256:${string}`; responseBytes: number };
  constructor(fixtureResponse?: { body: Uint8Array; contentType: string; fetchedAt: string; sha256: `sha256:${string}`; responseBytes: number }) { super(); this.fixtureResponse = fixtureResponse; }
  async fetchRaw(context: AdapterExecutionContext) { if (this.fixtureResponse) return { sourceId: this.sourceId, resourceId: this.resourceId, requestedUrl: "https://www.twse.com.tw/company/applylistingCsvAndHtml?selectType=Local&type=open_data", finalUrl: "https://www.twse.com.tw/company/applylistingCsvAndHtml?selectType=Local&type=open_data", ...this.fixtureResponse, httpStatus: 200, attemptCount: 1 }; return context.approvedHttpClient({ resource: getApprovedResource("11586", "11586-csv"), now: context.clock }); }
  parseRaw(response: { body: Uint8Array; contentType: string }): readonly Source11586Row[] { if (response.contentType !== "text/csv") throw new Error("CONTENT_TYPE_MISMATCH"); return parse11586Csv(new TextDecoder("utf-8", { fatal: true }).decode(response.body)); }
  normalize(rows: readonly Source11586Row[]): readonly NormalizedListingApplicationWithStage11586[] { return rows.map((row) => { const record = normalize11586Application(row); return { ...record, stage: deriveStage(record) }; }); }
  validateIntegrity(raw: readonly Source11586Row[], records: readonly NormalizedListingApplicationWithStage11586[]): IntegrityReport { const errors: AdapterDiagnostic[] = []; const warnings: AdapterDiagnostic[] = []; const conflicts: string[] = []; try { assertUnique11586Applications(records); } catch (e) { conflicts.push(e instanceof Error ? e.message : String(e)); errors.push({ stage: "integrity", code: "DUPLICATE_IDENTITY", message: conflicts[0] }); } if (raw.length !== records.length) errors.push({ stage: "integrity", code: "ROW_COUNT_MISMATCH", message: "raw and normalized row counts differ" }); for (const record of records) if (record.stage !== "listed_for_trading") warnings.push({ stage: "integrity", code: "PARTIAL_CHRONOLOGY", message: `application progression is partial for ${record.companyCode}`, recordIdentity: record.sourceRecordId }); const ok = errors.length === 0 && records.length > 0; return { status: ok ? (warnings.length ? "valid_with_warnings" : "valid") : "invalid", acceptedRecordCount: records.length, rejectedRecordCount: Math.max(0, raw.length - records.length), warningCount: warnings.length, errors, warnings, identityConflicts: conflicts, canPublishCandidate: ok }; }
}
export function create11586CsvAdapter(fixtureResponse?: ConstructorParameters<typeof Source11586CsvAdapter>[0]): Source11586CsvAdapter { return new Source11586CsvAdapter(fixtureResponse); }
