import { RepositoryError } from "./errors.ts";
import type { PipelineRepository, PipelineRepositoryTransaction, PublishedPointerUpdate } from "./contracts.ts";
import type { DatasetId, DatasetRecord, IngestionRunRecord, PublishedSnapshotPointer, SourceHealthRecord, SourceSnapshotRecord } from "./types.ts";
const clone = <T>(v: T): T => structuredClone(v);
export class InMemoryPipelineRepository implements PipelineRepository {
  private runs = new Map<string, IngestionRunRecord>(); private snapshots = new Map<string, SourceSnapshotRecord>(); private records = new Map<string, DatasetRecord[]>(); private pointers = new Map<DatasetId, PublishedSnapshotPointer>(); private health = new Map<string, SourceHealthRecord>();
  async createIngestionRun(run: IngestionRunRecord) { if (this.runs.has(run.runId)) throw new RepositoryError("RUN_ALREADY_EXISTS"); this.runs.set(run.runId, clone(run)); }
  async getIngestionRun(id: string) { return clone(this.runs.get(id)); }
  async createSnapshot(s: SourceSnapshotRecord) { if (this.snapshots.has(s.snapshotId)) throw new RepositoryError("SNAPSHOT_ALREADY_EXISTS"); const run = this.runs.get(s.runId); if (!run) throw new RepositoryError("RUN_NOT_FOUND"); if (run.datasetId !== s.datasetId || run.sourceId !== s.sourceId || run.resourceId !== s.resourceId) throw new RepositoryError("SNAPSHOT_RUN_MISMATCH"); this.snapshots.set(s.snapshotId, clone(s)); }
  async getSnapshot(id: string) { return clone(this.snapshots.get(id)); }
  async writeDatasetRecords(datasetId: DatasetId, snapshotId: string, rows: readonly DatasetRecord[]) { const snap = this.snapshots.get(snapshotId); if (!snap) throw new RepositoryError("SNAPSHOT_NOT_FOUND"); if (snap.datasetId !== datasetId || rows.some((r) => r.datasetId !== datasetId || r.snapshotId !== snapshotId)) throw new RepositoryError("RECORD_DATASET_MISMATCH"); const key = `${datasetId}:${snapshotId}`; const existing = this.records.get(key); if (existing) { if (JSON.stringify(existing) === JSON.stringify(rows)) return; throw new RepositoryError("RECORD_SET_CONFLICT"); } const ids = new Set<string>(); for (const r of rows) { if (ids.has(r.naturalIdentity)) throw new RepositoryError("DUPLICATE_NATURAL_IDENTITY"); ids.add(r.naturalIdentity); } this.records.set(key, clone([...rows].sort((a,b)=>a.naturalIdentity.localeCompare(b.naturalIdentity)))); }
  async persistIngestionCandidate(run: IngestionRunRecord, snapshot: SourceSnapshotRecord, rows: readonly DatasetRecord[]) { await this.createIngestionRun(run); await this.createSnapshot(snapshot); await this.writeDatasetRecords(snapshot.datasetId, snapshot.snapshotId, rows); }
  async readDatasetRecords(datasetId: DatasetId, snapshotId: string) { return clone(this.records.get(`${datasetId}:${snapshotId}`) ?? []); }
  async compareAndSetPublishedSnapshotPointer(datasetId: DatasetId, expected: string | null, pointer: PublishedSnapshotPointer) { const target = this.snapshots.get(pointer.currentSnapshotId); if (pointer.datasetId !== datasetId || !target) throw new RepositoryError("POINTER_TARGET_NOT_FOUND"); if (target.datasetId !== datasetId || target.sourceId !== pointer.sourceId || target.resourceId !== pointer.resourceId) throw new RepositoryError("POINTER_DATASET_MISMATCH"); const current = this.pointers.get(datasetId); if ((current?.currentSnapshotId ?? null) !== expected) return false; this.pointers.set(datasetId, clone(pointer)); return true; }
  async publishPointersAtomically(updates: readonly PublishedPointerUpdate[]) { const checks = updates.map((update) => { const target = this.snapshots.get(update.pointer.currentSnapshotId); if (!target || target.datasetId !== update.datasetId || update.pointer.datasetId !== update.datasetId || target.sourceId !== update.pointer.sourceId || target.resourceId !== update.pointer.resourceId) throw new RepositoryError("POINTER_DATASET_MISMATCH"); return (this.pointers.get(update.datasetId)?.currentSnapshotId ?? null) === update.expectedCurrentSnapshotId; }); if (checks.some((ok) => !ok)) return false; for (const update of updates) this.pointers.set(update.datasetId, clone(update.pointer)); return true; }
  async getPublishedSnapshotPointer(datasetId: DatasetId) { return clone(this.pointers.get(datasetId)); }
  async updateSourceHealth(next: SourceHealthRecord, expectedVersion: number) { const key = `${next.sourceId}:${next.resourceId}`; const current = this.health.get(key); if ((current?.version ?? 0) !== expectedVersion) throw new RepositoryError("SOURCE_HEALTH_VERSION_CONFLICT"); const saved = { ...clone(next), version: expectedVersion + 1 }; this.health.set(key, saved); return clone(saved); }
  async withTransaction<T>(operation: (tx: PipelineRepositoryTransaction) => Promise<T>) { const copy = new InMemoryPipelineRepository(); Object.assign(copy, { runs: clone(this.runs), snapshots: clone(this.snapshots), records: clone(this.records), pointers: clone(this.pointers), health: clone(this.health) }); try { const value = await operation(copy); Object.assign(this, { runs: copy.runs, snapshots: copy.snapshots, records: copy.records, pointers: copy.pointers, health: copy.health }); return value; } catch (e) { throw e; } }
}
