import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { create11406CsvAdapter } from "../../lib/pipeline/adapters/11406-csv.ts";
import { runSourceAdapterContractTests } from "../../lib/pipeline/adapters/contract-harness.ts";

const fixture = await readFile(new URL("../fixtures/source-verification/11406/csv-minimal.csv", import.meta.url));
const response = { sourceId: "11406", resourceId: "11406-csv", requestedUrl: "https://www.tpex.org.tw/storage/bond_publish/ISSBD5_data.csv", finalUrl: "https://www.tpex.org.tw/storage/bond_publish/ISSBD5_data.csv", fetchedAt: "2026-07-26T00:00:00.000Z", httpStatus: 200, contentType: "text/csv", responseBytes: fixture.byteLength, sha256: "sha256:11406", body: new Uint8Array(fixture), attemptCount: 1 };
const context = (patch = {}) => ({ runId: "11406-run", executionMode: "offline_fixture", clock: () => "2026-07-26T00:00:00.000Z", approvedHttpClient: async () => ({ ...response }), ...patch });

test("11406 adapter satisfies shared contract and uses approved CSV", async () => { await runSourceAdapterContractTests(() => create11406CsvAdapter(response)); });
test("11406 adapter normalizes bond terms and provenance without market data", async () => { const adapter = create11406CsvAdapter(); const result = await adapter.execute(context()); assert.equal(result.executionStatus, "succeeded"); assert.equal(result.records.length, 2); const bond = result.records[1]; assert.equal(bond.bondCode, "35221"); assert.equal(bond.issueDate, "2023-12-18"); assert.equal(bond.maturityDate, "2026-12-18"); assert.equal(bond.outstandingAmount, "123100000"); assert.equal(bond.putDates[0], "2025-12-18"); assert.equal(result.responseHash, "sha256:11406"); assert.equal(Object.hasOwn(bond, "stockPrice"), false); assert.equal(Object.hasOwn(bond, "volume"), false); });
test("11406 adapter rejects wrong content, duplicate bond identity and malformed rows", async () => { const wrong = await create11406CsvAdapter().execute(context({ approvedHttpClient: async () => ({ ...response, contentType: "application/json" }) })); assert.equal(wrong.executionStatus, "failed_parse"); const duplicateBody = Buffer.concat([fixture, fixture.subarray(fixture.indexOf(10) + 1)]); const dup = await create11406CsvAdapter().execute(context({ approvedHttpClient: async () => ({ ...response, body: new Uint8Array(duplicateBody) }) })); assert.equal(dup.executionStatus, "failed_parse"); });
test("11406 adapter never calls OpenAPI, bond_cb_daily, fallback or persistence", async () => { const urls = []; const result = await create11406CsvAdapter().execute(context({ approvedHttpClient: async ({ resource }) => { urls.push(resource.exactUrl); return { ...response }; } })); assert.deepEqual(urls, ["https://www.tpex.org.tw/storage/bond_publish/ISSBD5_data.csv"]); assert.equal(Object.hasOwn(result, "repository"), false); assert.equal(Object.hasOwn(result, "publishedSnapshotId"), false); });
