import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { create11586CsvAdapter } from "../../lib/pipeline/adapters/11586-csv.ts";
import { runSourceAdapterContractTests } from "../../lib/pipeline/adapters/contract-harness.ts";

const fixture = await readFile(new URL("../fixtures/source-verification/11586/csv-minimal.csv", import.meta.url));
const response = { sourceId: "11586", resourceId: "11586-csv", requestedUrl: "https://www.twse.com.tw/company/applylistingCsvAndHtml?selectType=Local&type=open_data", finalUrl: "https://www.twse.com.tw/company/applylistingCsvAndHtml?selectType=Local&type=open_data", fetchedAt: "2026-07-26T00:00:00.000Z", httpStatus: 200, contentType: "text/csv", responseBytes: fixture.byteLength, sha256: "sha256:11586", body: new Uint8Array(fixture), attemptCount: 1 };
const context = (patch = {}) => ({ runId: "11586-run", executionMode: "offline_fixture", clock: () => "2026-07-26T00:00:00.000Z", approvedHttpClient: async () => ({ ...response }), ...patch });

test("11586 adapter satisfies shared contract and uses approved CSV", async () => { await runSourceAdapterContractTests(() => create11586CsvAdapter(response)); });
test("11586 adapter derives stages and excludes underwriting price from normalized records", async () => { const result = await create11586CsvAdapter().execute(context()); assert.equal(result.executionStatus, "succeeded"); assert.equal(result.records.length, 2); assert.equal(result.records[0].stage, "listed_for_trading"); assert.equal(result.records[1].stage, "applied"); assert.equal(result.records[0].underwriters.length, 1); assert.equal(Object.hasOwn(result.records[0], "underwritingPrice"), false); assert.equal(result.responseHash, "sha256:11586"); });
test("11586 partial chronology is valid_with_warnings and remains candidate", async () => { const result = await create11586CsvAdapter().execute(context()); assert.equal(result.integrityReport.status, "valid_with_warnings"); assert.equal(result.integrityReport.canPublishCandidate, true); assert.ok(result.integrityReport.warningCount > 0); });
test("11586 adapter rejects wrong content, duplicate identity and malformed chronology", async () => { const wrong = await create11586CsvAdapter().execute(context({ approvedHttpClient: async () => ({ ...response, contentType: "application/json" }) })); assert.equal(wrong.executionStatus, "failed_parse"); const duplicate = Buffer.concat([fixture, fixture.subarray(fixture.indexOf(10) + 1)]); const dup = await create11586CsvAdapter().execute(context({ approvedHttpClient: async () => ({ ...response, body: new Uint8Array(duplicate) }) })); assert.equal(dup.executionStatus, "failed_parse"); });
test("11586 adapter never calls OpenAPI, fallback or persistence", async () => { const urls = []; const result = await create11586CsvAdapter().execute(context({ approvedHttpClient: async ({ resource }) => { urls.push(resource.exactUrl); return { ...response }; } })); assert.deepEqual(urls, ["https://www.twse.com.tw/company/applylistingCsvAndHtml?selectType=Local&type=open_data"]); assert.equal(Object.hasOwn(result, "repository"), false); });
