import assert from "node:assert/strict";
import test from "node:test";
import { InMemoryPipelineRepository } from "../../lib/pipeline/repositories/in-memory.ts";

const run = { runId: "run-1", datasetId: "94025", sourceId: "94025", resourceId: "94025-csv", executionMode: "offline_fixture", status: "running", startedAt: "2026-07-26T00:00:00.000Z", adapterVersion: "a", rawSchemaVersion: "r", domainSchemaVersion: "d", createdAt: "2026-07-26T00:00:00.000Z", updatedAt: "2026-07-26T00:00:00.000Z" };
const snapshot = { snapshotId: "snap-1", runId: "run-1", datasetId: "94025", sourceId: "94025", resourceId: "94025-csv", adapterVersion: "a", rawSchemaVersion: "r", domainSchemaVersion: "d", fetchedAt: "2026-07-26T00:00:00.000Z", responseHash: "sha256:x", responseBytes: 1, rawRowCount: 1, acceptedRecordCount: 1, rejectedRecordCount: 0, warningCount: 0, validationStatus: "valid", publicationEligibility: "eligible", createdAt: "2026-07-26T00:00:00.000Z" };
const record = { datasetId: "94025", snapshotId: "snap-1", naturalIdentity: "94025:1260:11506", value: { companyCode: "1260" } };

test("in-memory repository stores runs, snapshots and records with identity/idempotency", async () => { const repo = new InMemoryPipelineRepository(); await repo.createIngestionRun(run); await assert.rejects(() => repo.createIngestionRun(run), /RUN_ALREADY_EXISTS/); await repo.createSnapshot(snapshot); await repo.writeDatasetRecords("94025", "snap-1", [record]); assert.deepEqual(await repo.readDatasetRecords("94025", "snap-1"), [record]); await assert.rejects(() => repo.writeDatasetRecords("94025", "snap-1", [{ ...record, value: { companyCode: "x" } }]), /RECORD_SET_CONFLICT/); });
test("transaction commits atomically and rolls back on rejection", async () => { const repo = new InMemoryPipelineRepository(); await assert.rejects(() => repo.withTransaction(async (tx) => { await tx.createIngestionRun(run); throw new Error("boom"); })); assert.equal(await repo.getIngestionRun("run-1"), undefined); await repo.withTransaction(async (tx) => { await tx.createIngestionRun(run); }); assert.equal((await repo.getIngestionRun("run-1")).status, "running"); });
test("published pointer uses optimistic compare-and-set and source health versions", async () => { const repo = new InMemoryPipelineRepository(); await repo.createIngestionRun(run); await repo.createSnapshot(snapshot); const pointer = { datasetId: "94025", sourceId: "94025", resourceId: "94025-csv", currentSnapshotId: "snap-1", previousSnapshotId: null, publishedAt: "2026-07-26T00:00:00.000Z", publicationRunId: "run-1" }; assert.equal(await repo.compareAndSetPublishedSnapshotPointer("94025", null, pointer), true); assert.equal(await repo.compareAndSetPublishedSnapshotPointer("94025", null, pointer), false); const health = await repo.updateSourceHealth({ sourceId: "94025", resourceId: "94025-csv", status: "healthy", consecutiveFailureCount: 0, version: 1, updatedAt: "2026-07-26T00:00:00.000Z" }, 0); assert.equal(health.version, 1); await assert.rejects(() => repo.updateSourceHealth({ ...health, version: 2 }, 0), /SOURCE_HEALTH_VERSION_CONFLICT/); });
test("repository rejects cross-dataset snapshots and pointers", async () => { const repo = new InMemoryPipelineRepository(); await repo.createIngestionRun(run); await assert.rejects(() => repo.createSnapshot({ ...snapshot, datasetId: "28567" }), /SNAPSHOT_RUN_MISMATCH/); await repo.createSnapshot(snapshot); await assert.rejects(() => repo.compareAndSetPublishedSnapshotPointer("94025", null, { datasetId: "94025", sourceId: "28567", resourceId: "28567-csv", currentSnapshotId: "snap-1", previousSnapshotId: null, publishedAt: "2026-07-26T00:00:00.000Z", publicationRunId: "run-1" }), /POINTER_DATASET_MISMATCH/); });
